name: "Terraform"

on:
  push: 
    branches: ["main"]
    paths: ["src/**"]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs: 
  login:
    name: "AWS Login"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4

  init:
    name: "Terraform Init"
    runs-on: "ubuntu-latest"
    needs: login
    if: ${{ success() && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' && env.AWS_DEFAULT_REGION != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform init
        working-directory: ./src
        run: terraform init -var-file="dev.tfvars"
